project:
  type: website

website:
  title: "Matemática Aplicada"
  navbar:
    left:
      - icon: chat-dots
        text: Foro
        href: https://github.com/Matematica-Aplicada/matematica-aplicada.github.io/discussions    
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Matematica-Aplicada/matematica-aplicada.github.io
    theme: cosmo
    css: styles.css



